
workflows:
  android-debug:
    name: Medical History Android APK
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Generate Android project
        script: |
          flutter create --platforms=android --project-name my_medical_history .

      - name: Get packages
        script: |
          flutter pub get

      - name: Analyze code
        script: |
          flutter analyze lib/main.dart

      - name: Build debug APK
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk

